development:
  adapter: postgresql
  encoding: unicode
  database: pg_pbx_development
  pool: 5
  username: pg_pbx
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: pg_pbx_test
  pool: 5
  username: pg_pbx
  password: password
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: pg_pbx_production
  pool: 5
  username: pg_pbx
  password: password
  host: localhost
  port: 5432
