#encoding: utf-8
Location.create(id: 1,region: 15,name: "Provincia de Arica",capital: "Arica",code: "058")
Location.create(id: 2,region: 15,name: "Provincia de Parinacota",capital: "Putre",code: "058")
Location.create(id: 3,region: 1,name: "Provincia de Iquique",capital: "Iquique",code: "057")
Location.create(id: 4,region: 1,name: "Provincia del Tamarugal",capital: "Pozo Almonte",code: "057")
Location.create(id: 5,region: 2,name: "Provincia de Antofagasta",capital: "Antofagasta",code: "055")
Location.create(id: 6,region: 2,name: "Provincia de El Loa",capital: "Calama",code: "055")
Location.create(id: 7,region: 2,name: "Provincia de Tocopilla",capital: "Tocopilla",code: "055")
Location.create(id: 8,region: 3,name: "Provincia de Copiapó",capital: "Copiapó",code: "052")
Location.create(id: 9,region: 3,name: "Provincia de Chañaral",capital: "Chañaral",code: "052")
Location.create(id: 10,region: 3,name: "Provincia de Huasco",capital: "Vallenar",code: "051")
Location.create(id: 11,region: 4,name: "Provincia de Elqui",capital: "Coquimbo",code: "051")
Location.create(id: 12,region: 4,name: "Provincia de Choapa",capital: "Illapel",code: "053")
Location.create(id: 13,region: 4,name: "Provincia de Limarí",capital: "Ovalle",code: "053")
Location.create(id: 14,region: 5,name: "Provincia de Valparaíso",capital: "Valparaíso",code: "032")
Location.create(id: 15,region: 5,name: "Provincia de Isla de Pascua",capital: "Hanga Roa",code: "039")
Location.create(id: 16,region: 5,name: "Provincia de Los Andes",capital: "Los Andes",code: "034")
Location.create(id: 17,region: 5,name: "Provincia de Petorca",capital: "La Ligua",code: "033")
Location.create(id: 18,region: 5,name: "Provincia de Quillota",capital: "Quillota",code: "033")
Location.create(id: 19,region: 5,name: "Provincia de San Antonio",capital: "San Antonio",code: "035")
Location.create(id: 20,region: 5,name: "Provincia de San Felipe de Aconcagua",capital: "San Felipe",code: "034")
Location.create(id: 21,region: 6,name: "Provincia de Cachapoal",capital: "Rancagua",code: "072")
Location.create(id: 22,region: 6,name: "Provincia de Cardenal Caro",capital: "Pichilemu",code: "072")
Location.create(id: 23,region: 6,name: "Provincia de Colchagua",capital: "San Fernando",code: "072")
Location.create(id: 24,region: 7,name: "Provincia de Talca",capital: "Talca",code: "071")
Location.create(id: 25,region: 7,name: "Provincia de Cauquenes",capital: "Cauquenes",code: "073")
Location.create(id: 26,region: 7,name: "Provincia de Curicó",capital: "Curicó",code: "075")
Location.create(id: 27,region: 7,name: "Provincia de Linares",capital: "Linares",code: "073")
Location.create(id: 28,region: 8,name: "Provincia de Concepción",capital: "Concepción",code: "041")
Location.create(id: 29,region: 8,name: "Provincia de Arauco",capital: "Lebu",code: "041")
Location.create(id: 30,region: 8,name: "Provincia de Biobío",capital: "Los Ángeles",code: "043")
Location.create(id: 31,region: 8,name: "Provincia de Ñuble",capital: "Chillán",code: "042")
Location.create(id: 32,region: 9,name: "Provincia de Cautín",capital: "Temuco",code: "045")
Location.create(id: 33,region: 9,name: "Provincia de Malleco",capital: "Angol",code: "045")
Location.create(id: 34,region: 14,name: "Provincia de Valdivia",capital: "Valdivia",code: "063")
Location.create(id: 35,region: 14,name: "Provincia del Ranco",capital: "La Unión",code: "063")
Location.create(id: 36,region: 10,name: "Provincia de Llanquihue",capital: "Puerto Montt",code: "065")
Location.create(id: 37,region: 10,name: "Provincia de Chiloé",capital: "Castro",code: "065")
Location.create(id: 38,region: 10,name: "Provincia de Osorno",capital: "Osorno",code: "064")
Location.create(id: 39,region: 10,name: "Provincia de Palena",capital: "Chaitén",code: "065")
Location.create(id: 40,region: 11,name: "Provincia de Coyhaique",capital: "Coyhaique",code: "067")
Location.create(id: 41,region: 11,name: "Provincia de Aisén",capital: "Puerto Aisén",code: "067")
Location.create(id: 42,region: 11,name: "Provincia de Capitán Prat",capital: "Cochrane",code: "067")
Location.create(id: 43,region: 11,name: "Provincia de General Carrera",capital: "Chile Chico",code: "067")
Location.create(id: 44,region: 12,name: "Provincia de Magallanes",capital: "Punta Arenas",code: "061")
Location.create(id: 45,region: 12,name: "Provincia de la Antártica Chilena",capital: "Puerto Williams",code: "061")
Location.create(id: 46,region: 12,name: "Provincia de Tierra del Fuego",capital: "Porvenir",code: "061")
Location.create(id: 47,region: 12,name: "Provincia de Última Esperanza",capital: "Puerto Natales",code: "061")
Location.create(id: 48,region: 13,name: "Provincia de Santiago",capital: "Santiago",code: "02")
Location.create(id: 49,region: 13,name: "Provincia de Cordillera",capital: "Puente Alto",code: "02")
Location.create(id: 50,region: 13,name: "Provincia de Chacabuco",capital: "Colina",code: "02")
Location.create(id: 51,region: 13,name: "Provincia de Maipo",capital: "San Bernardo",code: "02")
Location.create(id: 52,region: 13,name: "Provincia de Melipilla",capital: "Melipilla",code: "02")
Location.create(id: 53,region: 13,name: "Provincia de Talagante",capital: "Talagante",code: "02")

admin = User.create(:first_name => 'Admin', :last_name => 'User', :email => 'cotocisternas@gmail.com', :password => 'password', :password_confirmation  => 'password')
admin.add_role :admin

Dialplan.rebuild_dialplan